# Generated by Django 4.2.5 on 2023-10-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='price',
        ),
    ]
