# Generated by Django 4.2.5 on 2023-10-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanagement', '0003_remove_rental_no_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
