# Generated by Django 4.2.5 on 2023-10-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanagement', '0004_alter_building_location_alter_owner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
